spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
    add-mappings: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  datasource:
    url: jdbc:oracle:thin:@10.251.253.47:1521:cdb
    hikari:
      password: c601!
      username: c60_dbowner
      driver-class-name: oracle.jdbc.OracleDriver
logging:
  file:
    path: ./log
    name: log
    max-size:
      1mb
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
server:
  servlet:
    session:
      cookie:
        http-only: false
        secure: false